"""
Django settings for inspection_engine project.

Generated by 'django-admin startproject' using Django 5.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import importlib
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env if present (local dev convenience). In production, env vars
# should be provided by the runtime environment.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "true").lower() in {"1", "true", "yes", "on"}

# Hosts: set ALLOWED_HOSTS="host1,host2" on Render (or rely on RENDER_EXTERNAL_HOSTNAME).
_default_allowed = ["localhost", "127.0.0.1"]
_allowed_env = os.getenv("ALLOWED_HOSTS", "").strip()
if _allowed_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_env.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = list(_default_allowed)
    _render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
    if _render_host:
        ALLOWED_HOSTS.append(_render_host)

# Loopback hosts are always allowed so `runserver`, tests, and curl keep working even when
# ALLOWED_HOSTS is set for a deployed hostname (e.g. Vercel) in `.env`.
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + _default_allowed))


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "forms",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inspection_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inspection_engine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    dj_database_url = importlib.import_module("dj_database_url")
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=60)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Leading slash so asset URLs resolve from site root (not relative to e.g. /admin/).
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR.parent / "frontend" / "dist" / "assets",
    BASE_DIR.parent / "frontend" / "dist",
]
STATIC_ROOT = BASE_DIR / "staticfiles"


def _static_root_populated(root: Path) -> bool:
    """True if collectstatic output exists (typical production / post-build local)."""
    if not root.is_dir():
        return False
    try:
        next(root.iterdir())
    except StopIteration:
        return False
    return True

# React index.html location
TEMPLATES[0]["DIRS"] = [BASE_DIR.parent / "frontend" / "dist"]

# WhiteNoise: use non-manifest storage so Vite's pre-hashed asset names are not
# re-hashed by Django collectstatic (Manifest storage breaks Vite builds).
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Configure WhiteNoise to serve React assets at their original URLs
WHITENOISE_ROOT = BASE_DIR.parent / "frontend" / "dist"
WHITENOISE_INDEX_FILE = True

# With DEBUG=0, WhiteNoise normally serves only STATIC_ROOT. Local runserver often has no
# collectstatic output yet, which breaks Django admin / Jazzmin CSS unless finders are on.
# Production builds run collectstatic (see build.sh), so STATIC_ROOT is populated and
# finders stay off for a normal deploy.
WHITENOISE_USE_FINDERS = DEBUG or not _static_root_populated(STATIC_ROOT)
WHITENOISE_AUTOREFRESH = DEBUG

# Media (for generated PDFs)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Frontend base URL used for generating copy-pasteable public links in admin.
# Override in `.env` via FRONTEND_BASE_URL.
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173").rstrip("/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}

# CORS: same-origin SPA on Django needs no CORS. Set CORS_ALLOWED_ORIGINS when the
# browser origin differs from the API (e.g. Vite dev server or split hosting).
_cors_env = os.getenv("CORS_ALLOWED_ORIGINS", "").strip()
if _cors_env:
    CORS_ALLOWED_ORIGINS = [
        o.strip().rstrip("/") for o in _cors_env.split(",") if o.strip()
    ]
elif DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Render terminates TLS; avoid redirect loops on internal HTTP.
    SECURE_SSL_REDIRECT = False

    _csrf_env = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
    if _csrf_env:
        CSRF_TRUSTED_ORIGINS = [
            o.strip().rstrip("/") for o in _csrf_env.split(",") if o.strip()
        ]
    else:
        CSRF_TRUSTED_ORIGINS = [
            f"https://{host}"
            for host in ALLOWED_HOSTS
            if host not in _default_allowed
        ]

# Jazzmin (admin theme) - minimal defaults
JAZZMIN_SETTINGS = {
    "site_title": "Inspection Engine Admin",
    "site_header": "Inspection Engine",
    "site_brand": "Inspection Engine",
    "welcome_sign": "Welcome",
}
