# Generated by Django 5.0.10 on 2026-01-15 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionInstance',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('organization_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspection_instance',
            },
        ),
        migrations.CreateModel(
            name='InspectionConfigVersion',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_versions', to='forms.inspectioninstance')),
            ],
            options={
                'db_table': 'inspection_config_version',
            },
        ),
        migrations.CreateModel(
            name='RecipientLink',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('config_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_links', to='forms.inspectionconfigversion')),
                ('inspection_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='forms.inspectioninstance')),
            ],
            options={
                'db_table': 'recipient_link',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('answers', models.JSONField()),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.inspectionconfigversion')),
                ('recipient_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='forms.recipientlink')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.AddConstraint(
            model_name='recipientlink',
            constraint=models.UniqueConstraint(fields=('inspection_instance', 'id'), name='uniq_recipient_link_per_instance'),
        ),
    ]
