# Generated by Django 5.0.10 on 2026-01-16 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_inspectionconfigversion_config_sha256_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioninstance',
            name='base_template',
            field=models.ForeignKey(blank=True, help_text='If this instance was cloned from a template, this points to the source template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_instances', to='forms.inspectioninstance'),
        ),
        migrations.AddField(
            model_name='inspectioninstance',
            name='kind',
            field=models.CharField(choices=[('template', 'Template'), ('campaign', 'Campaign')], default='campaign', max_length=16),
        ),
        migrations.AddField(
            model_name='inspectioninstance',
            name='submission_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/submissions/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pdf_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='AggregatedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/aggregated/')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('inspection_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_report', to='forms.inspectioninstance')),
            ],
            options={
                'db_table': 'aggregated_report',
            },
        ),
    ]
