# Generated by Django 5.0.10 on 2026-04-10 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_seed_sri_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('hospital_program_name', models.CharField(max_length=255)),
                ('logo', models.FileField(blank=True, null=True, upload_to='branding/logos/')),
                ('primary_color', models.CharField(default='#1F2937', max_length=7, validators=[django.core.validators.RegexValidator(message='primary_color must be a hex color in #RRGGBB format.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization_branding',
                'ordering': ('organization_id',),
            },
        ),
    ]
